name: Deploy to Namecheap cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./"
          remote_dir: "/public_html"
          delete: "false"
          exclude: >
            .git
            .github
            .gitignore
            .vscode
            node_modules
            worker
            tests
            README.md
